### ISSUE TITLE
Small bug and proposed fix in similarity weights

### ISSUE THREAD

**Issue by cbhurley** [markajoc/condvis#4]
If a numeric variable is constant, then the similarity weights returned are NaN.

This is because the scale for these variables is zero. So suggest the following fix:
Insert after
x.scaled <- scale(xc.num)
the four lines
  zeros <- attr(x.scaled, "scaled:scale") ==0
  attr(x.scaled, "scaled:scale")[zeros]<- 1
  attr(x.scaled, "scaled:center")[zeros]<- 0
  x.scaled[,zeros]<- xc.num[,zeros]
Then this variable won't count in calculating the similarity.

**Comment by markajoc** [comment]
Sorry, only seeing this now. Notifications weren't going to email! I suppose I had left this case out because I figured such things would be filtered out of the dataset in the model-fitting process before using condvis... but it is a valid dataset that should be treated properly! I'm surprised `base::scale` doesn't warn in this case. I'll have a think about what to do. Does this not arise with factors?

**Comment by cbhurley** [comment]
Hi Mark

My fix just checks if a var has sd=0, and if so it is omitted from the similarity calculation, this seemed the easiest option.

I’m not sure what happens if a var is a factor with levels a,b, and c and then then you are calculating weights when the observed level is d say.

I’ve been working on the condvis talk for sdss. I will send you and K the completed pdf, or upload it to dropbox or
gitlab.

Hope you are well

Catherine

------------------------------------------------------------------------------------------------------------------------
Dr. Catherine Hurley
Maynooth University Department of Mathematics & Statistics
------------------------------------------------------------------------------------------------------------------------

**Comment by markajoc** [comment]
I committed a fix for this on devel with https://github.com/markajoc/condvis/commit/188ed3c02667749cedfbfedaf4e3008422f377f9 which drops columns with zero variance for both factors and numerics. Please let me know if this does what you expect! I'll add a unit test and release a new version to CRAN in the next week.
